development:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292
  LANG: en_US.UTF-8
  MSG_KEY: use rake generate:msg_key 
  RACK_ENV: development
  REDISCLOUD_URL: put your redis url here
  SESSION_SECRET: use rake generate:session_secret


test:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292
  LANG: en_US.UTF-8
  MSG_KEY: use rake generate:msg_key 
  RACK_ENV: test
  REDISCLOUD_URL: put your redis url here
  SESSION_SECRET: use rake generate:session_secret



production:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292
  LANG: en_US.UTF-8
  MSG_KEY: use rake generate:msg_key 
  RACK_ENV: production
  REDISCLOUD_URL: put your redis url here
  SESSION_SECRET: use rake generate:session_secret